locale: "en-US"
site_theme: "default"
title: "Mehmet Eren Ahsen"
title_separator: "-"
name: "Mehmet Eren Ahsen"
description: "Assistant Professor at Gies College of Business working at the intersection of machine learning, healthcare, information systems, and operations."
url: "https://erenahsen.com"
baseurl: ""
repository: "ahsen1402/erenahsen-site"
remote_theme: "academicpages/academicpages.github.io@master"

include:
  - _pages

future: true
markdown: kramdown
permalink: /:categories/:title/

author:
  avatar: ""
  name: "Mehmet Eren Ahsen"
  bio: "Assistant Professor at Gies College of Business, University of Illinois Urbana-Champaign."
  location: "Champaign, Illinois"
  employer: "University of Illinois Urbana-Champaign"
  email: ""
  googlescholar: "https://scholar.google.com/citations?user=vFo_xZAAAAAJ&hl=tr&oi=ao"
  github: "ahsen1402"

publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
